name: Compile Rust Library

on:
    push:
        branches: ["*"]
    pull_request:
        branches: ["*"]

jobs:
    build:
        name: Build on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
                include:
                    - os: ubuntu-latest
                      target: x86_64-unknown-linux-gnu
                    - os: macos-latest
                      target: x86_64-apple-darwin
                    - os: windows-latest
                      target: x86_64-pc-windows-msvc

        steps:
            - uses: actions/checkout@v4

            - name: Install Rust
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  target: ${{ matrix.target }}
                  override: true

            - name: Build
              uses: actions-rs/cargo@v1
              with:
                  command: build
                  args: --release --target ${{ matrix.target }}

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: scarlet-${{ matrix.target }}
                  path: target/${{ matrix.target }}/release/libscarlet.*
                  retention-days: 7