name: Compile Rust Library

on:
    push:
        branches: [ "*" ]
    pull_request:
        branches: [ "*" ]

jobs:
    build:
        name: Build on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ ubuntu-latest, macos-latest, windows-latest ]
                include:
                    -   os: ubuntu-latest
                        target: x86_64-unknown-linux-gnu
                    -   os: macos-latest
                        target: x86_64-apple-darwin
                    -   os: windows-latest
                        target: x86_64-pc-windows-msvc

        steps:
            -   uses: actions/checkout@v4

            -   name: Install Rust
                uses: dtolnay/rust-toolchain@stable
                with:
                    toolchain: stable
                    targets: ${{ matrix.target }}


            -   name: Setup Node.js
                uses: actions/setup-node@v3
                with:
                    node-version: '22'

            -   name: Install dependencies
                run: npm ci

            -   name: Upload artifact
                uses: actions/upload-artifact@v4
                with:
                    name: scarlet-${{ matrix.target }}
                    path: target/
                    retention-days: 7

            -   name: Build Rust agent
                run: npm run build-agent-release

            -   name: Build for ${{ matrix.os }}
                run: |
                    if [ "${{ matrix.os }}" == "macos-latest" ]; then
                      npm run release:mac
                    else
                      npm run release:win
                    fi
                shell: bash

            - name: Upload artifacts
              uses: actions/upload-artifact@v3
              with:
                  name: scarlet-${{ matrix.os }}
                  path: |
                      dist/*.dmg
                      dist/*.exe
                      dist/*.zip
                  if-no-files-found: error